DROP TABLE Stg_DailyPrice;

CREATE TABLE Stg_DailyPrice (
	[SYMBOL] VARCHAR(50)
	,[SERIES] CHAR(10)
	,[OPEN] DECIMAL(10, 2)
	,[HIGH] DECIMAL(10, 2)
	,[LOW] DECIMAL(10, 2)
	,[CLOSE] DECIMAL(10, 2)
	,[LAST] DECIMAL(10, 2)
	,[PREVCLOSE] DECIMAL(10, 2)
	,[TOTTRDQTY] BIGINT
	,[TOTTRDVAL] DECIMAL(38, 2)
	,[TIMESTAMP] VARCHAR(15)
	,[TOTALTRADES] BIGINT
	,[ISIN] VARCHAR(50)
	,[FileName] VARCHAR(50)

	);

DROP TABLE if EXISTS Core_DailyPrice;

CREATE TABLE Core_DailyPrice (
	[SYMBOL] VARCHAR(50)
	,[SERIES] CHAR(10)
	,[OPEN] DECIMAL(10, 2)
	,[HIGH] DECIMAL(10, 2)
	,[LOW] DECIMAL(10, 2)
	,[CLOSE] DECIMAL(10, 2)
	,[LAST] DECIMAL(10, 2)
	,[PREVCLOSE] DECIMAL(10, 2)
	,[TOTTRDQTY] BIGINT
	,[TOTTRDVAL] DECIMAL(38, 2)
	,[STOCK_DATE] VARCHAR(15)
	,[TOTALTRADES] BIGINT
	,[ISIN] VARCHAR(50)
	,ROW_INSRT_TMS datetime 
	,ROW_UPDT_TMS datetime 
	,ROW_INS_USR Varchar(20)
	,ROW_UPD_USR Varchar(20)

	);


DROP TABLE How to apply for driving licence in UK 

CREATE TABLE STG_ActivityData (
	[SYMBOL] VARCHAR(50)
	,[SERIES] CHAR(10)
	,[DATE] VARCHAR(15)
	,[PREV_CLOSE] DECIMAL(10, 2)
	,[OPEN_PRICE] DECIMAL(10, 2)
	,[HIGH_PRICE] DECIMAL(10, 2)
	,[LOW_PRICE] DECIMAL(10, 2)
	,[LAST_PRICE] DECIMAL(10, 2)
	,[CLOSE_PRICE] DECIMAL(10, 2)
	,[AVG_PRICE] DECIMAL(10, 2)
	,[TTL_TRD_QNTY] BIGINT
	,[TURNOVER_LACS] DECIMAL(10, 2)
	,[NO_OF_TRADES] BIGINT
	,[DELIV_QTY] BIGINT
	,[DELIV_PER] DECIMAL(10, 2)
	,[FileName] VARCHAR(50)
	);


DROP TABLE if EXISTS Core_ActivityData

CREATE TABLE Core_ActivityData (
	[SYMBOL] VARCHAR(50)
	,[SERIES] CHAR(10)
	,[STOCK_DATE] VARCHAR(15)
	,[PREV_CLOSE] DECIMAL(10, 2)
	,[OPEN_PRICE] DECIMAL(10, 2)
	,[HIGH_PRICE] DECIMAL(10, 2)
	,[LOW_PRICE] DECIMAL(10, 2)
	,[LAST_PRICE] DECIMAL(10, 2)
	,[CLOSE_PRICE] DECIMAL(10, 2)
	,[AVG_PRICE] DECIMAL(10, 2)
	,[TTL_TRD_QNTY] BIGINT
	,[TURNOVER_LACS] DECIMAL(10, 2)
	,[NO_OF_TRADES] BIGINT
	,[DELIV_QTY] BIGINT
	,[DELIV_PER] DECIMAL(10, 2)
	,ROW_INSRT_TMS datetime 
	,ROW_UPDT_TMS datetime 
	,ROW_INS_USR Varchar(20)
	,ROW_UPD_USR Varchar(20)

	);
